pep8, add doc and allow saving fig or not in script compare irfs
cta-observatory/lstmcpipe pull request #149
Opened 2022-01-20 11:15 UTC by garciagenrique

2022-02-02 15:17 UTC, vuillaut requested changes

2022-02-02 15:17 UTC, vuillaut commented on lstmcpipe/scripts/script_compare_irfs.py
> +                        help='Save resulting figure',
implement with `action='store_false'` (remove type)

2022-02-02 15:24 UTC, vuillaut commented
> Why would you not want to save the figure? These scripts are not meant for interactive use, right?
> 
> Also the way I usually see this handled is to leave the `output_file` an empty string or `False` and then do:
> 
> ```python
> if output_file:
>     fig.savefig(output_file)
> else:
>     fig.show()
> ```
> 
> Does this even show the figure in the other case? Whats the point of calling the script?



> Why would you not want to save the figure? These scripts are not meant for interactive use, right?
> 
> Also the way I usually see this handled is to leave the `output_file` an empty string or `False` and then do:
> 
> ```python
> if output_file:
>     fig.savefig(output_file)
> else:
>     fig.show()
> ```
> 
> Does this even show the figure in the other case? Whats the point of calling the script?

I agree with `output_file=None` or `False` and the proposed implementation that would be much cleaner.

Then the script args can follow the same logic (save figure only if an outfile is passed).

Concerning the interactivity, I do use the **function** (not the script obviously) in notebooks at least  🤷‍♂️

2022-02-02 16:10 UTC, LukasNickel commented
> Concerning the interactivity, I do use the **function** (not the script obviously) in notebooks at least  man_shrugging

Of course, interactive plots are nice and all.
But this is meant to be used on the cluster in a scheduled job. There is no reason for interactivity there.
(Thats my first impression, I might miss something, which is why I asked for the reason)

2022-02-03 09:08 UTC, vuillaut commented
default None for outfile in function plot_comparison

2022-02-11 14:08 UTC, garciagenrique commented
> Concerning the interactivity, I do use the function (not the script obviously) in notebooks at least man_shrugging



> > Concerning the interactivity, I do use the **function** (not the script obviously) in notebooks at least  man_shrugging
> 
> Of course, interactive plots are nice and all. But this is meant to be used on the cluster in a scheduled job. There is no reason for interactivity there. (Thats my first impression, I might miss something, which is why I asked for the reason)

Everything is indeed expected to be run at the cluster as batched job. But some examples of the school were calling the function interactively, for example :). And I have the impression that if we would like to start comparing plots, this functionality might be useful

2022-02-11 14:11 UTC, garciagenrique commented
Thanks for the changes @vuillaut !

2022-02-11 14:11 UTC, merged