New test diffuse 4822
cta-observatory/lstmcpipe pull request #328
Opened 2022-06-20 13:05 UTC by giorgio-pirola

# New Prod config

## Prod_ID

## Short description of the config

## Why this config is needed

2022-06-23 07:31 UTC, vuillaut requested changes
Please change the date formatting everywhere to be consistent with other prods and list them by date order correctly

2022-06-23 07:31 UTC, vuillaut commented on production_configs/20220524_dec_4822_tuned_TestDIffuseGammas/lstmcpipe_config_2022-05-24_TestDiffuseGammas.yaml
> +    output: /fefs/aswg/data/mc/DL1/AllSky/24052022_dec_4822/TestingDataset/GammaDiffuse/node_theta_14.984_az_355.158_
the output date formatting is wrong
please use `YYYYMMDD` to be consistent with all other prods

2022-06-23 07:31 UTC, vuillaut commented on production_configs/20220524_dec_4822_tuned_TestDIffuseGammas/lstmcpipe_config_2022-05-24_TestDiffuseGammas.yaml
> +    output: /fefs/aswg/data/mc/DL1/AllSky/24052022_dec_4822/TestingDataset/GammaDiffuse/dl1_24_05_2022_dec_4822_node_theta_14.984_az_355.158__merged.h5
Same comment here, some consistency in the date would be better

2022-06-23 07:31 UTC, vuillaut commented on production_configs/20220524_dec_4822_tuned_TestDIffuseGammas/lstmcpipe_config_2022-05-24_TestDiffuseGammas.yaml
> +prod_id: 24052022_dec_4822
change to `20220524_dec_4822_tuned`

2022-06-23 07:34 UTC, vuillaut commented
Other comments:
- When opening the pull-request, the template should be filled with just a some info to help the reviewer (same info that is in the readme, so a simple copy/pasting should do).

- does this PR replaces #327 ?

2022-06-23 08:18 UTC, giorgio-pirola commented
> Other comments:
> 
> * When opening the pull-request, the template should be filled with just a some info to help the reviewer (same info that is in the readme, so a simple copy/pasting should do).
> * does this PR replaces [Test diffuse gammas 4822 #327](https://github.com/cta-observatory/lstmcpipe/pull/327) ?

Yes sorry, I opened 3 pull requests in total, but I'd like the last one "New test diffuse 4822" to replace the previous ones!

2022-06-23 08:22 UTC, garciagenrique commented
> > Other comments:
> > 
> > * When opening the pull-request, the template should be filled with just a some info to help the reviewer (same info that is in the readme, so a simple copy/pasting should do).
> > * does this PR replaces [Test diffuse gammas 4822 #327](https://github.com/cta-observatory/lstmcpipe/pull/327) ?
> 
> Yes sorry, I opened 3 pull requests in total, but I'd like the last one "New test diffuse 4822" to replace the previous ones!

Then close the previous PRs @giorgio-pirola , please

2022-06-23 10:00 UTC, vuillaut approved these changes

2022-06-24 13:22 UTC, merged

2022-06-24 13:27 UTC, giorgio-pirola commented
> I don't know why the tests are still failing, valid configs. Will work on the tests later, I merge.

Should I delete the branch?

2022-06-24 14:38 UTC, vuillaut commented
@giorgio-pirola I have fixed some issues with the config (see #329 and #330) and launched the prod.
However, I just realised you are producing IRFs with diffuse gammas without any background, is that really useful for high-level analysis?

2022-06-27 15:33 UTC, vuillaut commented
I had to fix a lot of tiny things and typos but I finally got the prod done:
```
/fefs/aswg/data/mc/{data_level}/AllSky/20220624_dec_4822_tuned/TestingDataset/dec_4822/
```