add efficiency cuts to dl2 to irfs options
cta-observatory/lstmcpipe pull request #477
Opened 2024-08-12 16:29 UTC by vuillaut

2024-08-20 09:37 UTC, morcuended requested changes

2024-08-20 09:37 UTC, morcuended commented on lstmcpipe/config/paths_config.py
> +                'options': '--gh-efficiency 0.7 --theta-containment 0.7 '
add "--energy-dependent-gh --energy-dependent-theta" I think by default global cuts are used

2024-08-20 09:37 UTC, morcuended commented on lstmcpipe/config/paths_config.py
> +                    'options': '--point-like --gh-efficiency 0.7 --theta-containment 0.7 ',
same as above

2024-08-22 07:21 UTC, vuillaut commented on lstmcpipe/config/paths_config.py
> +                'options': '--gh-efficiency 0.7 --theta-containment 0.7 '
right! thanks !

2024-08-26 07:25 UTC, morcuended approved these changes
looks good to me

2024-08-26 10:09 UTC, merged