Add new configuration for src15
cta-observatory/lstmcpipe pull request #500
Opened 2024-10-04 21:11 UTC by nikoliclisa

# New Prod config

Self check-list:

- [ ] I have checked the lstchain config, in particular for:
  - [ ] `az_tel` instead of `sin_az_tel` if data to be analyzed have been produced with lstchain <= v0.9.7
  - [ ] "increase_nsb" and "increase_psf" are provided in "image_modifier" (if used)
- [ ] I have checked the environment in the lstmcpipe config and it is the one used to analyse DL>1 data
- [ ] I have provided the command (in README), or script (in additionnal .py file) used to produce the lstmcpipe config

## Prod_ID

## Short description of the config

## Why this config is needed

2024-10-22 15:26 UTC, nikoliclisa commented
Hi @vuillaut 
Is there anything else that should be provided for the production?

2024-10-23 14:36 UTC, vuillaut requested changes

2024-10-23 14:36 UTC, vuillaut commented on production_configs/20240917_v0.10.12_src15_dec_min_2924_tuned/lstchain_config_2024-09-17.json
> +    }
Hi @nikoliclisa 
Sorry for the delay.
Thank you for the well documented readme.
The lstchain config should include the `image_modifier` config you produced.

2024-10-23 14:52 UTC, merged

2024-10-23 15:30 UTC, vuillaut commented
@nikoliclisa
This configuration cannot work, it starts from a source prod `20240917_v0.10.12_src15_dec_min_2924_tuned` that does not exist (it's yours).
You must start from an existing prod. In this case, the most recent base one is [20240131_allsky_v0.10.5_all_dec_base](https://github.com/cta-observatory/lstmcpipe/tree/master/production_configs/20240131_allsky_v0.10.5_all_dec_base).
Please reproduce the config (you will need to pull the changes I made to lstchain config to be able to push again on that branch).